# Generated by Django 4.2.6 on 2023-12-29 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debitnote',
            old_name='amount',
            new_name='amount_receivable',
        ),
        migrations.RenameField(
            model_name='debitnote',
            old_name='purchase_in',
            new_name='purchase_invoice',
        ),
        migrations.RemoveField(
            model_name='debitnote',
            name='cgst',
        ),
        migrations.RemoveField(
            model_name='debitnote',
            name='cr_amount',
        ),
        migrations.RemoveField(
            model_name='debitnote',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='debitnote',
            name='gst_per',
        ),
        migrations.RemoveField(
            model_name='debitnote',
            name='sgst',
        ),
        migrations.AddField(
            model_name='debitnote',
            name='gst_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='invoice_type',
            field=models.CharField(blank=True, choices=[('b2b', 'B2B'), ('b2c-l', 'B2C-L'), ('bsc', 'Bsc-O'), ('nil-rated', 'Nil-Rated'), ('advance received', 'Advance Received'), ('export', 'Export'), ('unregistered-local', 'Unregistered-Local'), ('unregistered-nonlocal', 'Unregistered-NonLocal')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='total_invoice',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='debitnote',
            name='attach_eway',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='debitnote',
            name='attach_invoice',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='debitnote',
            name='invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='debitnote',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='debitnote',
            name='month',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='debitnote',
            name='party_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
