# Generated by Django 4.2.6 on 2023-12-29 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_debitproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditnote',
            old_name='amount',
            new_name='amount_receivable',
        ),
        migrations.RenameField(
            model_name='creditnote',
            old_name='sales_in',
            new_name='sales_invoice',
        ),
        migrations.RemoveField(
            model_name='creditnote',
            name='cgst',
        ),
        migrations.RemoveField(
            model_name='creditnote',
            name='cr_amount',
        ),
        migrations.RemoveField(
            model_name='creditnote',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='creditnote',
            name='gst_per',
        ),
        migrations.RemoveField(
            model_name='creditnote',
            name='sgst',
        ),
        migrations.AddField(
            model_name='creditnote',
            name='gst_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='invoice_type',
            field=models.CharField(blank=True, choices=[('b2b', 'B2B'), ('b2c-l', 'B2C-L'), ('bsc', 'Bsc-O'), ('nil-rated', 'Nil-Rated'), ('advance received', 'Advance Received'), ('export', 'Export'), ('unregistered-local', 'Unregistered-Local'), ('unregistered-nonlocal', 'Unregistered-NonLocal')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='total_invoice',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='attach_eway',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='attach_invoice',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='month',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='party_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.CreateModel(
            name='CreditProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hsn', models.CharField(blank=True, max_length=50, null=True)),
                ('product_name', models.TextField(blank=True, null=True)),
                ('unit_of_measure', models.CharField(blank=True, max_length=50, null=True)),
                ('unit', models.IntegerField(blank=True, null=True)),
                ('rate', models.IntegerField(blank=True, null=True)),
                ('gst_per', models.IntegerField(blank=True, null=True)),
                ('taxable_amount', models.IntegerField(blank=True, null=True)),
                ('cgst', models.IntegerField(blank=True, null=True)),
                ('sgst', models.IntegerField(blank=True, null=True)),
                ('igst', models.IntegerField(blank=True, null=True)),
                ('credit_note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.creditnote')),
            ],
        ),
    ]
