# Generated by Django 4.2.5 on 2023-10-23 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_ownerdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('account_no', models.CharField(max_length=255)),
                ('ifsc', models.CharField(max_length=50)),
                ('account_type', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=255)),
                ('attachment', models.FileField(upload_to='')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.company')),
            ],
        ),
    ]
