# Generated by Django 4.2.6 on 2024-01-02 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_amount_creditnote_amount_receivable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='total_gst',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='total_tax_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
