# Generated by Django 4.2.6 on 2023-10-26 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_tan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerdetails',
            name='share',
            field=models.IntegerField(),
        ),
    ]
