# Generated by Django 4.2.4 on 2024-01-08 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_assetspurchasedbill_amount_assetspurchasedbill_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankstatement',
            old_name='name',
            new_name='bank_name',
        ),
    ]
