# Generated by Django 4.2.4 on 2024-01-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_loanvoucher_name_loanvoucher_bank_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetspurchasedbill',
            name='name',
        ),
        migrations.AddField(
            model_name='assetspurchasedbill',
            name='bank_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
