# Generated by Django 4.2.4 on 2024-01-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_assetspurchasedbill_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interestcertificate',
            name='name',
        ),
        migrations.AddField(
            model_name='interestcertificate',
            name='bank_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
