# Generated by Django 4.2.4 on 2024-01-18 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_interestcertificate_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_type', models.CharField(choices=[('gstr-1', 'GSTR-1'), ('gstr-3b', 'GSTR-3B'), ('gstr-4', 'GSTR-4'), ('gstr-5', 'GSTR-5'), ('gstr-5a', 'GSTR-5A'), ('gstr-6', 'GSTR-6'), ('gstr-7', 'GSTR-7'), ('gstr-8', 'GSTR-8'), ('gstr-9', 'GSTR-9'), ('gstr-10', 'GSTR-10'), ('gstr-11', 'GSTR-11'), ('cmp-8', 'CMP-8'), ('itc-04', 'ITC-04'), ('income-tax', 'Income-Tax'), ('tax-audit', 'Tax-Audit'), ('sft', 'SFT')], max_length=50)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('month', models.CharField(max_length=100)),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly'), ('half-year', 'Half-yearly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=50)),
                ('computation', models.FileField(upload_to='')),
                ('client_review', models.BooleanField()),
                ('remark', models.BooleanField()),
                ('acknowledgement', models.FileField(upload_to='')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.company')),
            ],
        ),
    ]
