# Generated by Django 4.2.5 on 2023-10-30 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_pan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Msme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msme_number', models.CharField(max_length=255)),
                ('msme_login', models.CharField(max_length=255)),
                ('msme_password', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=500)),
                ('filling_freq', models.CharField(choices=[('monthly', 'Monthly'), ('half-year', 'Half-yearly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=100)),
                ('attachment', models.FileField(upload_to='')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.company')),
            ],
        ),
    ]
