# Generated by Django 4.2.4 on 2024-01-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_financialyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialyear',
            name='from_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
