# Generated by Django 4.2.4 on 2024-01-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_financialyear_from_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialyear',
            name='client_review',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financialyear',
            name='computation',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='financialyear',
            name='frequency',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('half-year', 'Half-yearly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='financialyear',
            name='month',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='financialyear',
            name='remark',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financialyear',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
