# Generated by Django 4.2.5 on 2024-01-29 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_financialyear_client_review_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxFirm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_firm', models.CharField(max_length=122)),
                ('date_of_incorporation', models.DateField()),
                ('contact_person', models.CharField(max_length=122)),
                ('entity_type', models.CharField(choices=[('proprietorship', 'Proprietorship'), ('partnership', 'Partnership'), ('private_ltd', 'Private Ltd'), ('public_ltd', 'Public Ltd'), ('huf', 'HUF'), ('llp', 'LLP'), ('llc', 'LLC'), ('aop', 'AOP'), ('trust', 'Trust')], max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='tax_firm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.taxfirm'),
        ),
    ]
