# Generated by Django 4.2.5 on 2024-01-30 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_taxfirm_company_tax_firm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialyear',
            name='remark',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
