# Generated by Django 4.2.5 on 2024-01-30 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_financialyear_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialyear',
            name='acknowledgement',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='financialyear',
            name='return_type',
            field=models.CharField(blank=True, choices=[('gstr-1', 'GSTR-1'), ('gstr-3b', 'GSTR-3B'), ('gstr-4', 'GSTR-4'), ('gstr-5', 'GSTR-5'), ('gstr-5a', 'GSTR-5A'), ('gstr-6', 'GSTR-6'), ('gstr-7', 'GSTR-7'), ('gstr-8', 'GSTR-8'), ('gstr-9', 'GSTR-9'), ('gstr-10', 'GSTR-10'), ('gstr-11', 'GSTR-11'), ('cmp-8', 'CMP-8'), ('itc-04', 'ITC-04'), ('income-tax', 'Income-Tax'), ('tax-audit', 'Tax-Audit'), ('sft', 'SFT')], max_length=50, null=True),
        ),
    ]
