# Generated by Django 4.2.5 on 2023-11-07 06:23

import api.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_assetspurchasedbill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetspurchasedbill',
            name='month',
            field=models.CharField(choices=[('01', 'Janauary'), ('02', 'February'), ('03', 'March'), ('04', 'April'), ('05', 'May'), ('06', 'June'), ('07', 'July'), ('08', 'August'), ('09', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], max_length=50),
        ),
        migrations.AlterField(
            model_name='assetspurchasedbill',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2018), api.models.max_value_current_year], verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='bankstatement',
            name='month',
            field=models.CharField(choices=[('01', 'Janauary'), ('02', 'February'), ('03', 'March'), ('04', 'April'), ('05', 'May'), ('06', 'June'), ('07', 'July'), ('08', 'August'), ('09', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], max_length=50),
        ),
        migrations.AlterField(
            model_name='bankstatement',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2018), api.models.max_value_current_year], verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='interestcertificate',
            name='month',
            field=models.CharField(choices=[('01', 'Janauary'), ('02', 'February'), ('03', 'March'), ('04', 'April'), ('05', 'May'), ('06', 'June'), ('07', 'July'), ('08', 'August'), ('09', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], max_length=50),
        ),
        migrations.AlterField(
            model_name='interestcertificate',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2018), api.models.max_value_current_year], verbose_name='year'),
        ),
    ]
