# Generated by Django 4.2.5 on 2024-01-30 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_acknowledgementfile_financial_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Financial2Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computation', models.FileField(blank=True, null=True, upload_to='computation_files/')),
                ('acknowledgement', models.FileField(blank=True, null=True, upload_to='acknowledgement_files/')),
                ('date_field', models.DateField()),
            ],
        ),
    ]
