# Generated by Django 4.2.5 on 2023-11-08 09:33

import api.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_tdscertificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanvoucher',
            name='month',
            field=models.CharField(choices=[('janauary', 'Janauary'), ('february', 'February'), ('march', 'March'), ('april', 'April'), ('may', 'May'), ('june', 'June'), ('july', 'July'), ('august', 'August'), ('september', 'September'), ('october', 'October'), ('november', 'November'), ('december', 'December')], max_length=50),
        ),
        migrations.AlterField(
            model_name='loanvoucher',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2018), api.models.max_value_current_year], verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='tdscertificate',
            name='month',
            field=models.CharField(choices=[('janauary', 'Janauary'), ('february', 'February'), ('march', 'March'), ('april', 'April'), ('may', 'May'), ('june', 'June'), ('july', 'July'), ('august', 'August'), ('september', 'September'), ('october', 'October'), ('november', 'November'), ('december', 'December')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tdscertificate',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2018), api.models.max_value_current_year], verbose_name='year'),
        ),
    ]
