# Generated by Django 4.2.5 on 2024-01-30 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_financial2year_date_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financial2year',
            name='date_field',
        ),
    ]
