# Generated by Django 4.2.4 on 2024-01-31 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_financial2year_acknowledgement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='YourModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('computation', models.FileField(upload_to='computation/')),
                ('acknowledgement', models.FileField(upload_to='acknowledgement/')),
            ],
        ),
    ]
