# Generated by Django 4.2.5 on 2023-11-15 04:02

import api.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_as26'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('janauary', 'Janauary'), ('february', 'February'), ('march', 'March'), ('april', 'April'), ('may', 'May'), ('june', 'June'), ('july', 'July'), ('august', 'August'), ('september', 'September'), ('october', 'October'), ('november', 'November'), ('december', 'December')], max_length=50)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2018), api.models.max_value_current_year], verbose_name='year')),
                ('type', models.CharField(choices=[('mutual-fund', 'Mutual-Fund'), ('equity', 'Equity'), ('fd', 'Fd'), ('others', 'Others')], max_length=100)),
                ('attachment', models.FileField(upload_to='')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
