# Generated by Django 4.2.4 on 2024-01-31 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_yourmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yourmodel',
            name='acknowledgement',
        ),
        migrations.RemoveField(
            model_name='yourmodel',
            name='computation',
        ),
        migrations.CreateModel(
            name='ComputationFileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='computation/')),
                ('your_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computation', to='api.yourmodel')),
            ],
        ),
        migrations.CreateModel(
            name='AcknowledgementFileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='acknowledgement/')),
                ('your_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgement', to='api.yourmodel')),
            ],
        ),
    ]
