# Generated by Django 4.2.5 on 2023-11-16 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_incometaxreturn'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_name', models.CharField(max_length=250)),
                ('month', models.DateField(blank=True, null=True)),
                ('invoice_no', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('amount', models.CharField(blank=True, max_length=200, null=True)),
                ('cgst', models.CharField(blank=True, max_length=255, null=True)),
                ('sgst', models.CharField(blank=True, max_length=255, null=True)),
                ('tds', models.CharField(blank=True, max_length=255, null=True)),
                ('tcs', models.CharField(blank=True, max_length=255, null=True)),
                ('in_amount', models.CharField(blank=True, max_length=255, null=True)),
                ('attach_invoice', models.FileField(upload_to='')),
                ('attach_eway', models.FileField(upload_to='')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DebitNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('party_name', models.CharField(max_length=250)),
                ('invoice_no', models.CharField(max_length=255)),
                ('invoice_date', models.DateField()),
                ('amount', models.CharField(max_length=200)),
                ('cgst', models.CharField(max_length=255)),
                ('sgst', models.CharField(max_length=255)),
                ('tds', models.CharField(max_length=255)),
                ('tcs', models.CharField(max_length=255)),
                ('cr_amount', models.CharField(max_length=255)),
                ('attach_invoice', models.FileField(upload_to='')),
                ('attach_eway', models.FileField(upload_to='')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('purchase_in', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.purchaseinvoice')),
            ],
        ),
    ]
