# Generated by Django 4.2.5 on 2024-02-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_rename_date_yourmodel_from_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yourmodel',
            name='client_review',
            field=models.BooleanField(default=False),
        ),
    ]
