# Generated by Django 4.2.5 on 2023-11-18 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_creditnote_gst_per_debitnote_gst_per_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='in_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
