# Generated by Django 4.2.5 on 2023-11-24 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_purchaseinvoice_in_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='amount_receivable',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='gst_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='hsn',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='igst',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='invoice_type',
            field=models.CharField(blank=True, choices=[('b2b', 'B2B'), ('b2c-l', 'B2C-L'), ('bsc', 'Bsc-O'), ('nil-rated', 'Nil-Rated'), ('advance received', 'Advance Received'), ('export', 'Export'), ('unregistered-local', 'Unregistered-Local'), ('unregistered-nonlocal', 'Unregistered-NonLocal')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='taxable_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='unit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='unit_of_measure',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
