# Generated by Django 4.2.5 on 2023-12-07 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_purchaseinvoice_amount_receivable_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseinvoice',
            old_name='amount',
            new_name='rate',
        ),
        migrations.RenameField(
            model_name='purchaseinvoice',
            old_name='in_amount',
            new_name='total_invoice',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='booking_date',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='is_reverse',
        ),
    ]
