# Generated by Django 4.2.5 on 2023-12-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_rename_amount_purchaseinvoice_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='party_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
