# Generated by Django 4.2.5 on 2024-02-05 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_yourmodel_client_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxfirm',
            name='gst',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='taxfirm',
            name='pan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='taxfirm',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='taxfirm',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
