# Generated by Django 4.2.5 on 2023-12-14 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_purchaseinvoice_party_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='cgst',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='description',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='gst_per',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='hsn',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='igst',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='sgst',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='taxable_amount',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='unit_of_measure',
        ),
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hsn', models.CharField(blank=True, max_length=50, null=True)),
                ('product_name', models.TextField(blank=True, null=True)),
                ('unit_of_measure', models.CharField(blank=True, max_length=50, null=True)),
                ('unit', models.IntegerField(blank=True, null=True)),
                ('rate', models.IntegerField(blank=True, null=True)),
                ('gst_per', models.IntegerField(blank=True, null=True)),
                ('taxable_amount', models.IntegerField(blank=True, null=True)),
                ('cgst', models.IntegerField(blank=True, null=True)),
                ('sgst', models.IntegerField(blank=True, null=True)),
                ('igst', models.IntegerField(blank=True, null=True)),
                ('purchase_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.purchaseinvoice')),
            ],
        ),
    ]
