# Generated by Django 4.2.4 on 2024-02-06 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_taxfirm_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxfirm',
            name='date_of_incorporation',
            field=models.DateField(blank=True, null=True),
        ),
    ]
