# Generated by Django 4.2.5 on 2023-12-19 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_remove_purchaseinvoice_cgst_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='attach_eway',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='attach_invoice',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
