# Generated by Django 4.2.5 on 2024-02-19 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_rename_share_ownerdetails_default_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='share',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='ownerdetails',
            name='default_share',
            field=models.IntegerField(),
        ),
    ]
