# Generated by Django 4.2.4 on 2024-02-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_company_share_alter_ownerdetails_default_share'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ptrc',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
