# Generated by Django 4.2.4 on 2024-02-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_alter_ptrc_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gst',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='msme',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='pan',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='ptec',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
