# Generated by Django 4.2.4 on 2024-02-21 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_alter_gst_attachment_alter_msme_attachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='udyamaadhar',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
