# Generated by Django 4.2.4 on 2024-02-23 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_alter_udyamaadhar_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetails',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
