# Generated by Django 4.2.4 on 2024-02-23 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_alter_bankdetails_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankstatement',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
