# Generated by Django 4.2.4 on 2024-02-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_alter_bankstatement_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='as26',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='assetspurchasedbill',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='interestcertificate',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='loanvoucher',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='tdscertificate',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
