# Generated by Django 4.2.4 on 2024-02-23 09:29

import api.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_alter_as26_attachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='as26',
            name='month',
            field=models.CharField(blank=True, choices=[('janauary', 'Janauary'), ('february', 'February'), ('march', 'March'), ('april', 'April'), ('may', 'May'), ('june', 'June'), ('july', 'July'), ('august', 'August'), ('september', 'September'), ('october', 'October'), ('november', 'November'), ('december', 'December')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='as26',
            name='year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2018), api.models.max_value_current_year], verbose_name='year'),
        ),
    ]
