# Generated by Django 4.2.4 on 2024-03-02 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_alter_as26_month_alter_as26_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='gst_per',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
